server:
  port: 8877

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myInterfaceTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course
    username: root
    password: Aixiaoyaxuan1087.

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*


